### ISSUE TITLE
Define GHA - GCP CD Pipeline

### ISSUE THREAD

**Issue by Sinclert** [nyudlts/ultraviolet#97]
This issue describes the necessity to have a _Continuous Deployment (CD)_ pipeline working **daily** during the duration of each sprint, and **discretionally** (upon version update, or tag creation), during the rest of the time. The deployment will be based on GCP and GCP products.

The initial idea involves:
- Automatic building of the Docker image.
- Automatic pushing of Docker image to the [GCP Registry](https://cloud.google.com/container-registry).
- Automatic launching of Docker container in[ GCP Cloud Run](https://cloud.google.com/run).

### Challenges
Versioning will work differently when operating on a _daily_ VS _discretional_ manner.

- **Daily:** version will be set by the current date.
- **Discretional:** version will be set by the [.uv-version](https://github.com/nyudlts/ultraviolet/blob/main/.uv-version) file.

### TODOs:
- [ ] Bureaucracy: Ask for GCP project with _Cloud Registry_ and _Cloud Run_ APIs activated.
- [ ] Bureaucracy: Ask for _Service Account_(S.A.) creation, with _Cloud Registry_ and _Cloud Run_... admin permissions? 🤷🏻‍♂️ 
- [ ] Bureaucracy: Ask for a _Service account_ (S.A.) **key**, to be used as secret when authenticating GitHub Actions and GCP.
- [ ] Software: save S.A. key within this project [secrets tab](https://github.com/nyudlts/ultraviolet/settings/secrets/actions) (**only admin users**).
- [ ] Software: define GitHub Actions workflow.

---

cc @ekate

**Comment by ekate** [comment]
@Sinclert I think I need to apologize. I tried to use GCP calculator to estimate costs and it made me think about the details of this project - there will be 4 additional containers which need to communicate with each other and you will need CloudSql instance of postgres. Or alternatively we can leave the services running on the host but then we can not tear the host down and again will have to take care of network issue... I think It does not worth your time and effort . There is a simpler solution - I will create a deployment account on github and will setup a cronjob to run builds every night using this account.

**Comment by Sinclert** [comment]
Closing for now.

It may be worth considering at some point in the future.
